# Generated by Django 2.1 on 2018-08-27 15:04

import carv.core.models
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfigurations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_resource_roles', django.contrib.postgres.fields.jsonb.JSONField(default=carv.core.models.default_roles, help_text='A list of json objects {id, role, color(hexadecimal string), active}')),
            ],
            options={
                'verbose_name': 'System Configurations',
            },
        ),
    ]
